<?php

/**
 * @file
 * Contains book_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function book_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the book_migration module.
    case 'help.page.book_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Book migration from CSV') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function book_migration_theme() {
  $theme = [];

  return $theme;
}
