<?php

/**
 * @file
 * Contains migrate_source_example_db.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_source_example_db_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_source_example_db module.
    case 'help.page.migrate_source_example_db':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example module that provides content migration from DB.') . '</p>';
      return $output;

    default:
  }
}
